import { defineCourse, type LessonTopic } from "@/content/course-contract";

const topics = (...titles: readonly string[]): readonly LessonTopic[] => titles.map((title, index) => ({
  id: `topic-${index + 1}`,
  title,
  description: `Розібрати ${title} та критерії його застосування у високонавантаженій системі.`,
}));

export const highLoadArchitectureCourse = defineCourse({
  id: "high-load-architecture",
  slug: "high-load-architecture",
  title: "Архітектура високонавантажених систем",
  description: "Від оцінки навантаження до відмовостійкого multi-region System Design.",
  duration: "≈24 години",
  level: "Middle → Senior",
  status: "published",
  accent: "HL",
  legacyPath: "/legacy/index.html#lesson-1",
  modules: [
    {
      id: "high-load-foundations",
      position: 1,
      title: "Основи високих навантажень",
      summary: "Перекладаємо бізнес-вимоги у вимірювані технічні характеристики.",
      lessons: [
        {
          id: "high-load-01",
          moduleId: "high-load-foundations",
          position: 1,
          title: "Що таке високонавантажена система",
          durationMinutes: 35,
          summary: "Відрізняємо навантаження від доступності та знаходимо перші bottlenecks.",
          topics: [
            { id: "high-load", title: "High Load", description: "Система обробляє великий або нерівномірний потік роботи." },
            { id: "high-availability", title: "High Availability", description: "Сервіс залишається доступним під час відмов окремих компонентів." },
            { id: "throughput-latency", title: "Throughput, latency і response time", description: "Розділяємо обсяг виконаної роботи та час очікування однієї відповіді." },
            { id: "traffic-metrics", title: "RPS, RPM і concurrent users", description: "Описуємо інтенсивність запитів та одночасну активність користувачів." },
            { id: "resource-bounds", title: "CPU-bound та I/O-bound", description: "Різні bottlenecks потребують різних способів масштабування." },
          ],
          practice: {
            title: "Оцінити YouTube Analytics Dashboard",
            tasks: ["Порахувати приблизне навантаження", "Визначити запити за секунду", "Знайти потенційні вузькі місця"],
            deliverable: "Розрахунок average і peak RPS зі списком bottlenecks та припущень.",
            validation: { expectedSuccess: "Бізнес-вимоги переведені у RPS, concurrency, traffic і capacity.", expectedFailures: ["High Load помилково прирівняно до High Availability", "Не враховано peak factor"] },
          },
          outcome: "Ти можеш перевести бізнес-вимоги у технічні показники.",
          legacyAnchor: "#lesson-1",
        },
        {
          id: "high-load-02", moduleId: "high-load-foundations", position: 2,
          title: "Функціональні та нефункціональні вимоги", durationMinutes: 55,
          summary: "Фіксуємо функції системи та вимірювані quality attributes.",
          topics: topics("Functional requirements", "Scalability", "Availability", "Reliability", "Maintainability", "Security", "Consistency", "Accessibility як системна вимога", "SLA, SLO та SLI"),
          practice: { title: "Сформувати вимоги до accessibility-аудиту", tasks: ["Задати максимальний час перевірки", "Визначити кількість одночасних аудитів", "Визначити retention результатів", "Розрахувати допустимий downtime"], deliverable: "Таблиця functional requirements, SLI, SLO та перевірних acceptance criteria.", validation: { expectedSuccess: "Кожна нефункціональна вимога має метрику, ціль і часовий інтервал.", expectedFailures: ["Використано слова «швидко» або «надійно» без чисел", "SLA переплутано зі SLI"] } },
          outcome: "Ти можеш перетворити очікування від продукту на перевірні системні вимоги.", legacyAnchor: "#lesson-2",
        },
        {
          id: "high-load-03", moduleId: "high-load-foundations", position: 3,
          title: "Оцінка навантаження", durationMinutes: 60,
          summary: "Робимо back-of-the-envelope calculations до вибору технологій.",
          topics: topics("Back-of-the-envelope calculations", "Кількість користувачів", "Read/write ratio", "Середній розмір запиту", "Обсяг збережених даних", "Мережевий трафік", "Пікове та середнє навантаження"),
          practice: { title: "Розрахувати capacity audit-платформи", tasks: ["Порахувати перевірки за день", "Оцінити кількість воркерів", "Оцінити місце для звітів за рік"], deliverable: "Capacity sheet із формулами, одиницями вимірювання та запасом.", validation: { expectedSuccess: "Усі оцінки узгоджені між throughput, workers, storage і network traffic.", expectedFailures: ["Змішанано біти та байти", "Використано лише average load без піку"] } },
          outcome: "Ти можеш швидко оцінити ресурси й перевірити реалістичність архітектури.", legacyAnchor: "#lesson-3",
        },
      ],
    },
    {
      id: "architecture-design", position: 2, title: "Архітектурний дизайн",
      summary: "Будуємо high-level architecture і вибираємо межі компонентів.",
      lessons: [
        {
          id: "high-load-04", moduleId: "architecture-design", position: 4,
          title: "Як проєктувати систему", durationMinutes: 70,
          summary: "Проходимо системний дизайн від уточнення вимог до trade-offs.",
          topics: topics("System Design Interview", "Уточнення вимог", "API design", "Data model", "High-level architecture", "Пошук bottlenecks", "Швидкість, складність та ціна"),
          practice: { title: "Намалювати першу audit-архітектуру", tasks: ["З’єднати Next.js Client, API Gateway, Audit Service, Queue, Workers і storage", "Позначити sync та async boundaries", "Знайти bottlenecks"], deliverable: "High-level схема з потоком запиту й поясненими компромісами.", validation: { expectedSuccess: "Довгий аудит відокремлений від HTTP request через queue і workers.", expectedFailures: ["Клієнт звертається безпосередньо до БД", "Аудит виконується синхронно всередині HTTP-запиту"] } },
          outcome: "Ти можеш послідовно побудувати й захистити першу версію System Design.", legacyAnchor: "#lesson-4",
        },
        {
          id: "high-load-05", moduleId: "architecture-design", position: 5,
          title: "Монолітна архітектура", durationMinutes: 55,
          summary: "Проєктуємо модульний моноліт без клубка залежностей.",
          topics: topics("Modular monolith", "Layered architecture", "Controller, service, repository", "Переваги моноліту", "Коли не потрібні мікросервіси", "Контроль залежностей"),
          practice: { title: "Структурувати один backend", tasks: ["Виділити audits, users, reports, notifications і billing", "Визначити public API модулів", "Заборонити циклічні залежності"], deliverable: "Структура src/ з відповідальністю кожного модуля.", validation: { expectedSuccess: "Модулі мають чіткі межі й не звертаються до внутрішніх repository інших модулів.", expectedFailures: ["Спільний global service знає про всі модулі", "Controller містить бізнес-логіку"] } },
          outcome: "Ти розумієш, як побудувати моноліт, який пізніше можна масштабувати.", legacyAnchor: "#lesson-5",
        },
        {
          id: "high-load-06", moduleId: "architecture-design", position: 6,
          title: "Мікросервісна архітектура", durationMinutes: 65,
          summary: "Визначаємо service boundaries без distributed monolith.",
          topics: topics("Service boundaries", "Bounded context", "Окремі бази даних", "Синхронна та асинхронна комунікація", "Переваги й недоліки мікросервісів", "Distributed monolith", "Service discovery"),
          practice: { title: "Розділити audit-платформу на сервіси", tasks: ["Виділити User, Audit, Worker, Report і Notification Service", "Призначити ownership даних", "Вибрати протоколи взаємодії"], deliverable: "Service map з межами даних і контрактами.", validation: { expectedSuccess: "Кожен сервіс володіє своєю відповідальністю та даними.", expectedFailures: ["Усі сервіси спільно змінюють одну схему БД", "Кожна операція утворює довгий синхронний ланцюжок"] } },
          outcome: "Ти можеш обґрунтовано визначити межі сервісів і ціну розподіленої системи.", legacyAnchor: "#lesson-6",
        },
        {
          id: "high-load-07", moduleId: "architecture-design", position: 7,
          title: "Архітектурні стилі", durationMinutes: 65,
          summary: "Порівнюємо стилі за вимогами, складністю та операційною ціною.",
          topics: topics("Layered architecture", "Hexagonal architecture", "Clean architecture", "Event-driven architecture", "Serverless", "CQRS", "Event sourcing", "Pipeline architecture"),
          practice: { title: "Порівняти три підходи", tasks: ["Оцінити модульний моноліт", "Оцінити мікросервіси", "Оцінити event-driven architecture", "Обґрунтувати вибір"], deliverable: "Decision record із критеріями та trade-offs.", validation: { expectedSuccess: "Вибір випливає з вимог audit-системи, а не з популярності технології.", expectedFailures: ["Стиль названо без критеріїв", "Не враховано operational complexity"] } },
          outcome: "Ти можеш порівнювати архітектурні стилі та аргументувати рішення.", legacyAnchor: "#lesson-7",
        },
      ],
    },
    {
      id: "service-communication", position: 3, title: "API та взаємодія сервісів",
      summary: "Проєктуємо зовнішні контракти та надійну асинхронну обробку.",
      lessons: [
        {
          id: "high-load-08", moduleId: "service-communication", position: 8,
          title: "Проєктування API", durationMinutes: 65,
          summary: "Вибираємо протокол і створюємо стабільний контракт lifecycle аудиту.",
          topics: topics("REST", "GraphQL", "gRPC", "WebSocket", "Webhook", "Polling", "Long polling", "Idempotency", "Pagination", "Versioning", "Rate limiting"),
          practice: { title: "Спроєктувати Audit API", tasks: ["Описати POST, GET report і DELETE endpoints", "Визначити queued, running, completed, failed, cancelled", "Додати idempotency та error responses"], deliverable: "API contract із status codes, schemas та lifecycle transitions.", validation: { expectedSuccess: "POST повертає стабільний audit ID, а повтор запиту є idempotent.", expectedFailures: ["Довга операція повертає 200 лише після завершення", "Статуси допускають неможливі переходи"] } },
          outcome: "Ти можеш спроєктувати передбачуваний API для тривалих процесів.", legacyAnchor: "#lesson-8",
        },
        {
          id: "high-load-09", moduleId: "service-communication", position: 9,
          title: "Синхронна та асинхронна обробка", durationMinutes: 70,
          summary: "Виносимо довгі процеси у durable background jobs.",
          topics: topics("Довгі HTTP-запити", "Background jobs", "Message broker", "Producer та consumer", "RabbitMQ, Kafka, Redis Streams, AWS SQS", "Retry", "Dead-letter queue", "Duplicate messages", "At-most-once та at-least-once"),
          practice: { title: "Побудувати asynchronous audit flow", tasks: ["Повернути 202 Accepted", "Передати job через Queue до Worker", "Зберегти статус у Database", "Обробити retries і duplicates"], deliverable: "Client → API → Queue → Worker → Database із failure policy.", validation: { expectedSuccess: "API швидко повертає 202, а consumer є idempotent.", expectedFailures: ["HTTP connection чекає завершення аудиту", "Retry може нескінченно дублювати side effects"] } },
          outcome: "Ти можеш надійно виконувати довгі задачі поза життєвим циклом HTTP-запиту.", legacyAnchor: "#lesson-9",
        },
      ],
    },
    {
      id: "data-systems", position: 4, title: "Робота з даними",
      summary: "Вибираємо сховища, масштабуємо дані та контролюємо консистентність.",
      lessons: [
        {
          id: "high-load-10", moduleId: "data-systems", position: 10,
          title: "Реляційні бази даних", durationMinutes: 70,
          summary: "Проєктуємо PostgreSQL schema та запити під реальні access patterns.",
          topics: topics("PostgreSQL", "Нормалізація", "Primary key і foreign key", "Індекси", "Query execution plan", "Транзакції", "ACID", "Connection pooling", "N+1 проблема", "Prisma у високонавантажених системах"),
          practice: { title: "Спроєктувати relational model", tasks: ["Створити users, projects, audits, audit_pages, issues, audit_events", "Додати foreign keys", "Додати індекси для частих запитів"], deliverable: "ER model та список indexes, пов’язаний з query patterns.", validation: { expectedSuccess: "Індекси відповідають filters, joins і ordering найчастіших запитів.", expectedFailures: ["Індекс додано на кожну колонку без access pattern", "N+1 запити залишилися непоміченими"] } },
          outcome: "Ти можеш спроєктувати PostgreSQL schema та перевірити її продуктивність.", legacyAnchor: "#lesson-10",
        },
        {
          id: "high-load-11", moduleId: "data-systems", position: 11,
          title: "NoSQL та вибір бази", durationMinutes: 60,
          summary: "Вибираємо сховище за моделлю доступу, а не за брендом.",
          topics: topics("Document databases", "Key-value storage", "Wide-column databases", "Search engines", "PostgreSQL проти MongoDB", "Redis", "Elasticsearch/OpenSearch", "Object storage", "Polyglot persistence"),
          practice: { title: "Розподілити дані між сховищами", tasks: ["Розмістити користувачів і результати", "Розмістити скріншоти та PDF", "Розмістити логи", "Розмістити тимчасові статуси"], deliverable: "Storage decision matrix із consistency, query і retention requirements.", validation: { expectedSuccess: "Кожен тип даних має обґрунтоване primary storage.", expectedFailures: ["Redis використано як єдине довготривале сховище", "Великі binary files зберігаються в основній БД без причини"] } },
          outcome: "Ти можеш застосувати polyglot persistence без зайвої складності.", legacyAnchor: "#lesson-11",
        },
        {
          id: "high-load-12", moduleId: "data-systems", position: 12,
          title: "Реплікація, партиціювання та шардинг", durationMinutes: 75,
          summary: "Розподіляємо 100 млн записів без hot shard і втрати керованості.",
          topics: topics("Primary та replica", "Read replicas", "Replication lag", "Partitioning", "Horizontal sharding", "Shard key", "Hot shard", "Consistent hashing", "Міграція даних між shard-ами"),
          practice: { title: "Спроєктувати storage для 100 млн issues", tasks: ["Вибрати partition і shard keys", "Розподілити reads", "Передбачити rebalancing", "Врахувати replication lag"], deliverable: "Data distribution scheme з growth і migration plan.", validation: { expectedSuccess: "Shard key рівномірно розподіляє write load і підтримує основні queries.", expectedFailures: ["Один великий tenant створює hot shard", "Код припускає миттєву консистентність replica"] } },
          outcome: "Ти можеш масштабувати зберігання й передбачити operational risks розподілу даних.", legacyAnchor: "#lesson-12",
        },
        {
          id: "high-load-13", moduleId: "data-systems", position: 13,
          title: "Консистентність даних", durationMinutes: 75,
          summary: "Забезпечуємо доставку повідомлення після атомарного завершення аудиту.",
          topics: topics("Strong consistency", "Eventual consistency", "CAP theorem", "Distributed transactions", "Optimistic locking", "Pessimistic locking", "Race condition", "Saga pattern", "Transactional outbox"),
          practice: { title: "Виправити втрату notification", tasks: ["Завершити аудит і записати outbox event в одній транзакції", "Опублікувати event окремим relay", "Зробити consumer idempotent"], deliverable: "Outbox flow із transaction boundary, retry та deduplication.", validation: { expectedSuccess: "Audit completion і outbox record комітяться атомарно.", expectedFailures: ["Notification відправляється до commit", "Event губиться між update аудиту й publish"] } },
          outcome: "Ти можеш забезпечити надійну міжсервісну дію без distributed transaction.", legacyAnchor: "#lesson-13",
        },
      ],
    },
    {
      id: "scaling-performance", position: 5, title: "Масштабування та продуктивність",
      summary: "Масштабуємо compute і delivery layer та знімаємо навантаження кешем.",
      lessons: [
        {
          id: "high-load-14", moduleId: "scaling-performance", position: 14,
          title: "Вертикальне масштабування", durationMinutes: 55,
          summary: "Порівнюємо більший сервер із кількома меншими після profiling.",
          topics: topics("Збільшення CPU, RAM і диска", "Переваги та обмеження", "Оптимізація до масштабування", "Profiling", "Memory leaks", "Connection limits", "Database bottlenecks"),
          practice: { title: "Порівняти scale up і scale out", tasks: ["Оцінити сервер 16 CPU", "Оцінити чотири сервери по 4 CPU", "Порівняти availability, cost і complexity"], deliverable: "Decision record з виміряним bottleneck і точкою перегляду рішення.", validation: { expectedSuccess: "Рішення враховує не лише CPU, а й SPOF, connections та licensing/cost.", expectedFailures: ["Масштабування обрано без profiling", "Більший сервер помилково вважається high availability"] } },
          outcome: "Ти можеш визначити, коли scale up є достатнім і коли потрібен scale out.", legacyAnchor: "#lesson-14",
        },
        {
          id: "high-load-15", moduleId: "scaling-performance", position: 15,
          title: "Горизонтальне масштабування", durationMinutes: 65,
          summary: "Робимо API stateless і запускаємо багато взаємозамінних copies.",
          topics: topics("Stateless application", "Load balancer", "Round robin", "Least connections", "Health checks", "Sticky sessions", "Autoscaling", "Container orchestration", "Kubernetes концептуально"),
          practice: { title: "Масштабувати API горизонтально", tasks: ["Додати Load Balancer", "Запустити API-1, API-2, API-3", "Винести session state", "Додати health checks"], deliverable: "Stateless API topology з routing та failure handling.", validation: { expectedSuccess: "Будь-який healthy API instance може обробити будь-який запит.", expectedFailures: ["Session зберігається лише в пам’яті instance", "Load balancer надсилає трафік unhealthy instance"] } },
          outcome: "Ти можеш підготувати застосунок до незалежного горизонтального масштабування.", legacyAnchor: "#lesson-15",
        },
        {
          id: "high-load-16", moduleId: "scaling-performance", position: 16,
          title: "Кешування", durationMinutes: 70,
          summary: "Зменшуємо reads із бази та контролюємо stale data і stampede.",
          topics: topics("Browser cache", "CDN", "Application cache", "Redis", "Cache-aside", "Write-through", "Write-behind", "TTL", "Cache invalidation", "Cache stampede", "Distributed locks"),
          practice: { title: "Додати cache layers", tasks: ["Кешувати список аудитів", "Кешувати dashboard statistics", "Кешувати готові звіти", "Кешувати user settings"], deliverable: "Cache policy з key, TTL, invalidation та fallback для кожних даних.", validation: { expectedSuccess: "Cache strategy зменшує DB reads і визначає прийнятну stale window.", expectedFailures: ["Немає invalidation policy", "Одночасний miss створює cache stampede"] } },
          outcome: "Ти можеш зменшити кількість звернень до бази без неконтрольованої застарілості.", legacyAnchor: "#lesson-16",
        },
        {
          id: "high-load-17", moduleId: "scaling-performance", position: 17,
          title: "CDN та робота зі статичними файлами", durationMinutes: 60,
          summary: "Виносимо великі immutable assets з основного application server.",
          topics: topics("Edge locations", "Static assets", "Object storage", "Presigned URL", "Image optimization", "Відео і великі файли", "Gzip та Brotli", "HTTP/2 та HTTP/3", "Next.js CDN і caching strategies"),
          practice: { title: "Винести screenshots і PDF reports", tasks: ["Зберігати файли в object storage", "Видавати presigned URL", "Доставляти public assets через CDN", "Визначити cache headers"], deliverable: "File delivery flow з ownership, access control і lifecycle policy.", validation: { expectedSuccess: "Application server не проксіює кожен великий файл.", expectedFailures: ["Bucket із приватними звітами відкритий public", "Mutable URL кешується назавжди без versioning"] } },
          outcome: "Ти можеш безпечно й ефективно доставляти великі статичні файли.", legacyAnchor: "#lesson-17",
        },
      ],
    },
    {
      id: "reliability-observability", position: 6, title: "Надійність та спостережуваність",
      summary: "Вимірюємо систему, переживаємо відмови й збираємо фінальний design.",
      lessons: [
        {
          id: "high-load-18", moduleId: "reliability-observability", position: 18,
          title: "Моніторинг, логування та алертинг", durationMinutes: 75,
          summary: "Пов’язуємо metrics, logs і traces з actionable alerts.",
          topics: topics("Metrics, logs, traces", "Observability", "Structured logging", "Correlation ID", "Distributed tracing", "OpenTelemetry", "Prometheus", "Grafana", "Application performance monitoring", "Error rate", "p50, p95, p99", "Alert fatigue"),
          practice: { title: "Створити dashboard і alerts", tasks: ["Візуалізувати queue size, processing duration, failure rate, API latency, DB connections і worker CPU", "Алертити error rate понад 5%", "Алертити queue понад 1 000", "Алертити p95 API понад 1 секунду"], deliverable: "Dashboard, alert rules і короткий runbook для кожного alert.", validation: { expectedSuccess: "Alerts прив’язані до user impact і мають owner/runbook.", expectedFailures: ["Alert створено на кожен spike без тривалості", "Dashboard показує average без p95/p99"] } },
          outcome: "Ти можеш побудувати observability, яка допомагає діагностувати, а не створює шум.", legacyAnchor: "#lesson-18",
        },
        {
          id: "high-load-19", moduleId: "reliability-observability", position: 19,
          title: "Відмовостійкість і фінальний System Design", durationMinutes: 120,
          summary: "Проєктуємо повну audit-платформу й перевіряємо її failure scenarios.",
          topics: topics("Single point of failure", "Redundancy", "Failover", "Circuit breaker", "Timeout", "Retry with exponential backoff", "Graceful degradation", "Backup", "Disaster recovery", "RPO та RTO", "Multi-region architecture", "Chaos engineering"),
          practice: { title: "Фінальний System Design", tasks: ["Підтримати 100 000 users і 10 000 audits/hour", "Перевіряти до 500 pages на site", "Зберігати results 3 роки", "Забезпечити 99,9% availability", "Додати retry, PDF/VPAT, live status і незалежне scaling API/workers"], deliverable: "Повна схема, capacity calculations, data model, API, failure policies та RPO/RTO.", validation: { expectedSuccess: "Архітектура витримує задане навантаження й відмову критичних компонентів із заявленими RPO/RTO.", expectedFailures: ["Залишено single point of failure", "API і workers неможливо масштабувати окремо", "Retry не має backoff, limit або DLQ"] } },
          outcome: "Ти можеш спроєктувати й аргументовано захистити production-ready високонавантажену систему.", legacyAnchor: "#lesson-19",
        },
      ],
    },
  ],
});
